/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Todo {
  /** 完了しているか */
  completed: boolean;
  /** 完了日時 */
  completedAt: number;
  /** 作成日時 */
  createdAt: number;
  /** Todo ごとに一意な ID */
  id: string;
  /** テキスト */
  text: string;
}
