/**
 * Generated by orval v6.25.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface UpdateTodo {
  /** 完了しているか */
  completed: boolean;
  /** テキスト */
  text: string;
}
